### ISSUE TITLE
No instance in created

### ISSUE THREAD

**Issue by francogrex** [Hakorr/A.C.A.S#9]
I followed the instructions exactly as stated. It remains stuck on trying to connect to instance. Both chrome and firefox browsers. I also tried several chess sites. Nothing works. Therefore it is not a fault in installation or use, it is a probably a newly introduced bug in the project itself.

**Comment by Hakorr** [comment]
>  It remains stuck on trying to connect to instance.

Can you share the console log, any errors you see?

Everything seems to work for me, tested Chess.com and Lichess.org.

**Comment by francogrex** [comment]
The issue report I had send above was based on Firefox (Nightly) and Google Chrome browsers running on Linux (Bunsenlabs https://www.bunsenlabs.org/). I tested on Chrome running on Windows 10 using the script and Tampermonkey, I confirm it works as expected. If you want you can close this here or keep it open until I can confirm/dis-confirm the issue on Linux and any specificity to that platform.

**Comment by Hakorr** [comment]
Can you check the developer console on the browser to check for any errors?

**Comment by francogrex** [comment]
There are two errors, this one doesn't seem to be significant: A.C.A.S/assets/images/backgrounds/default.png 404 (Not Found)

However the second error here seems to be the main issue:
stockfish.js:25 Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): Compiling function #56 failed: Wasm SIMD unsupported @+8636). Build with -s ASSERTIONS=1 for more info.
    at M (stockfish.js:25:112)
    at stockfish.js:138:293
M	@	stockfish.js:25
(anonymous)	@	stockfish.js:138
await in (anonymous) (async)		
BackendInstance	@	acas-backend-instance.js:136
createInstance	@	acas-backend-manager.js:14
(anonymous)	@	index.js:34
(anonymous)	@	🏆 [＃1 Chess Cheat] …System).user.js:155
(anonymous)	@	🏆 [＃1 Chess Cheat] …System).user.js:153
receivePackets	@	🏆 [＃1 Chess Cheat] …System).user.js:152
loop	@	🏆 [＃1 Chess Cheat] … System).user.js:38
await in loop (async)		
setIntervalAsync	@	🏆 [＃1 Chess Cheat] … System).user.js:47
registerListener	@	🏆 [＃1 Chess Cheat] …System).user.js:145
(anonymous)	@	index.js:22

**Comment by Hakorr** [comment]
> Wasm SIMD unsupported

I guess Chrome and Firefox don't support this WASM feature on Linux?

Do you have any other Linux distros you could try?

**Comment by francogrex** [comment]
It's almost definitely the Stockfish.wasm that is problematic on (at least my Linux). I have tinkered with the code a little bit and managed to get it working by replacing Stockfish.wasm with an old Stockfish.js (version 5 - with some additional modifications to acas-backend-instance.js to get them to talk to each other)... But although functional it is very slow and even unstably slow (plus an old Stockfish version like that is not what people would want to use nowadays). Anyway maybe we can close this issue at this stage now. Thanks.

**Comment by Hakorr** [comment]
Maybe in the future it could use Stockfish.js when WASM is not supported. There's quite new versions of Stockfish ported to JS.

Anyway, thanks for the report and for doing little experiments to figure out the root cause.
